Customer/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import login, logout_then_login
from . import views

app_name='Customer'
urlpatterns = [
   url(r'^customer_view/(?P<pk>\d+)$', views.customer_view, name='customer_view'),
   url(r'^customer_edit/(?P<pk>\d+)$', views.customer_update, name='customer_edit'),
   url(r'^customer_delete/(?P<pk>\d+)$', views.customer_delete, name='customer_delete'),
   url(r'^customer_new$', views.customer_create, name='customer_new'),
   url(r'^index$', views.index, name='index')
   ]

Ecommerce2/urls.py
from django.conf.urls import url,include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/', include('login.urls')),
    url(r'^', include('Customer.urls'))
]

login/urls.py
from django.conf.urls import url,include
from django.contrib.auth.views import login, logout_then_login
from . import views
app_name='login'
urlpatterns = [
    url(r'^$', views.login, name='login'),
]

Customer/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

class Customer(models.Model):
    customerID = models.IntegerField(primary_key=True)
    fName = models.CharField(max_length=500)
    lName = models.CharField(max_length=100)
    joinDate = models.CharField(max_length=1000)
    primaryEmailID = models.CharField(max_length=1000)
    preferEmail = models.BooleanField(default=True)
    emailNotification = models.BooleanField()
    billType = models.CharField(max_length=20)
    contactNo = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    def get_absolute_url(self):
        return reverse('Customer:home')
    def __str__(self):
        return self.fName +" "+ self.lName

class Service_Request(models.Model):
    customerID = models.ForeignKey(Customer,on_delete=models.CASCADE)
    requestID = models.IntegerField(primary_key=True)
    requestType = models.CharField(max_length=500)
    subscriptionDate = models.CharField(max_length=100)
    fulfillmentDate = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000)

class Shipping_Address(models.Model):
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)
    shipAddID = models.IntegerField(primary_key=True)
    state = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    zip = models.CharField(max_length=10)
    street = models.CharField(max_length=100)



class Payment_Method(models.Model):
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)
    pmtMethodID = models.IntegerField(primary_key=True)
    cardNo = models.CharField(max_length=100)
    cardHolderName = models.CharField(max_length=20)
    cardType = models.CharField(max_length=50)
    expDate = models.CharField(max_length=20)
    cvvNo = models.IntegerField()
    def __str__(self):
        return self.cardHolderName +"-"+ self.cardNo

class Billing_Address(models.Model):
    PmtMethodID = models.ForeignKey(Payment_Method, on_delete=models.CASCADE)
    billAddID = models.IntegerField(primary_key=True)
    state = models.CharField(max_length=10)
    city = models.CharField(max_length=50)
    zip = models.CharField(max_length=10)
    street = models.CharField(max_length=100)

class Security (models.Model):
    qID = models.IntegerField(primary_key=True)
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000)
    answer = models.CharField(max_length=1000)

class Product_type(models.Model):
    productID = models.IntegerField(primary_key=True)
    productType = models.CharField(max_length=100)

class Settings_of_interst(models.Model):
    productID = models.ForeignKey(Product_type, on_delete=models.CASCADE)
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)
    interestID = models.IntegerField(primary_key=True)
#class Song(models.Model):
#   album = models.ForeignKey(Album, on_delete=models.CASCADE)
#   file_type = models.CharField(max_length=10)
#   song_title = models.CharField(max_length=250)

login/models.py
from django.db import models
from django.contrib import admin

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
class UserAdmin(admin.ModelAdmin):
    list_display = ('username','password')
admin.site.register(User,UserAdmin)

Customer/views.py
from django.shortcuts import render
from .models import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from login.views import *

# Create your views here.
class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['customerID', 'fName', 'lName', 'joinDate', 'primaryEmailID', 'preferEmail', 'emailNotification',
              'billType', 'contactNo','password']

def index(request, template_name='customer/index.html'):

    ctx = {}

    return render(request, template_name, ctx)





class CustomerCreate(CreateView):
    model = Customer
    fields = ['customerID', 'fName', 'lName', 'joinDate', 'primaryEmailID', 'preferEmail', 'emailNotification',
              'billType', 'contactNo', 'password']


def customer_view(request, pk):
    customers = Customer.objects.filter(customerID=pk)
    ctx = {}
    ctx["customers"] = customers
    return render(request, 'customer/book_view.html', ctx)


def customer_create(request, template_name='customer/book_form.html'):
    form = CustomerForm(request.POST or None)
    if form.is_valid():
        form.save()
        return customer_view(request,form.cleaned_data['customerID'])
    ctx = {}
    ctx["form"] = form
    return render(request, template_name, ctx)


def customer_update(request, pk, template_name='customer/book_form.html'):
    customer = get_object_or_404(Customer, customerID=pk)
    form = CustomerForm(request.POST or None, instance=customer)
    if form.is_valid():
        form.save()
        return customer_view(request,pk)
    ctx = {}
    ctx["form"] = form
    ctx["customer"] = customer
    return render(request, template_name, ctx)


def customer_delete(request, pk, template_name='customer/book_confirm_delete.html'):
    customer = get_object_or_404(Customer, customerID=pk)
    if request.method == 'POST':
        customer.delete()
        return redirect('login:login')
    ctx = {}
    ctx["object"] = customer
    ctx["customer"] = customer
    return render(request, template_name, ctx)

login/views.py
from django.shortcuts import render,render_to_response
from django.http import HttpResponseRedirect
from login.models import  User
from django import forms
from Customer.views import customer_update
from Customer.models import Customer

# Create your views here.
class UserForm(forms.Form):
    username = forms.CharField(label='customerID',max_length=50)
    password = forms.CharField(label='password',widget=forms.PasswordInput)

def login(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            customer = Customer.objects.filter(customerID__exact = username,password__exact = password)
            if customer:
                return render_to_response('../../Customer/templates/customer/book_view.html',{'customers':customer})
            else:
                return HttpResponseRedirect('/login/')
    else:
        uf = UserForm()
    print(request)
    return render_to_response('login.html',{'uf':uf})

Customer/templates/customer/book_confirm_delete.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Landing Page - Customer Service Platform</title>

    <!-- Bootstrap Core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="all" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css'%}" rel="stylesheet"/>

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css"/>
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
.img-circle{

	height:230px;
	width:250px;
}
body {
	background-color: #F0F0F0;
}
</style>

</head>

<body >

<div class="text-center">
<img src="{% static 'img/delete.jpeg' %}" class="img-circle" alt=""/>

</div>
<div class="text-center">
  <div class="content-section-a">

        <div class="container">


                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                        <form method="post">{% csrf_token %}
                        <h2>Confirm to delete "{{ object }}" ?</h2> <br>

                         <input type="submit" value="Confirm" />
                        </form>
                <br>
                        <a href="{% url 'login:login' %}"><input type="submit" value="Cancel" /></a>


            </div>
                </div>

        </div>
  </div>
</div>

</body>

</html>

Customer/templates/customer/book_form.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Landing Page - Customer Service Platform</title>

    <!-- Bootstrap Core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="all" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css'%}" rel="stylesheet"/>

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css"/>
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style type="text/css">
body {
	background-color: #F0F0F0;
}
</style>
</head>


<body>
<div class="intro-header2">
<h1>Customer Information Registration</h1>

</div>
<br>
<div class="text-center">
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <br>
    <input type="submit" value="Submit" />
</form>
</div>
</body>
</html>

Customer/templates/customer/book_view.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Landing Page - Customer Service Platform</title>

    <!-- Bootstrap Core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="all" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css'%}" rel="stylesheet"/>

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css"/>
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<div class="intro-header1">
<h1>Welcome to Customer Platform</h1>


<br>
<br>

{% for cus in customers %}
    <div style="background:rgba(0,0,0,0.3)">
<table class="table table-bordered" style="text-align:left" >
<tr>


        <th> Customer Information </th>
        <th> </th>
        <tr>
        <td>Customer Name: </td> <td>{{cus.fName}}  {{ cus.lName }}</td>
        </tr>
        <tr>
        <td>joinDate: </td><td>{{cus.joinDate}}</td>
        </tr>
        <tr>
        <td>primaryEmailID: </td><td>{{cus.primaryEmailID}}</td>
        </tr>
        <tr>
        <td>preferEmail: </td><td>{{cus.preferEmail}}</td>
        </tr>
        <tr>
        <td> emailNotification: </td><td>{{cus.emailNotification}}</td>
        </tr>
        <tr>
        <td>billType: </td><td>{{cus.billType}}</td>
        </tr>
        <tr>
        <td>contactNo: </td><td>{{cus.contactNo}}</td>
        </tr>
</table>
    </div>



    <br>
    <br>


    <div class="text-center">

<a href="{% url 'Customer:customer_edit' cus.customerID %}"> <input type="button" value="edit"></a>
        &nbsp;  &nbsp;
<a href="{% url 'Customer:customer_delete' cus.customerID %}"> <input type="button" value="delete"></a>
    </div>
    </div>

 {% endfor %}
</body>
</html>

Customer/templates/customer/customer_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customer-create</title>
</head>
<body>
<h1>Enter the customer data</h1>
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <label> {{field.label_tag}}</label>
        {{field}}<br><br>
    {% endfor %}
<button type="submit">Submit</button>
</form>

</body>
</html>

Customer/templates/customer/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Landing Page - Customer Service Platform</title>

    <!-- Bootstrap Core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="all" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css'%}" rel="stylesheet"/>

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css"/>
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
          </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Services</a>
                    </li>
                    <li>
                       <a href="{% url 'login:login' %}">Login</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
      <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Landing Page</h1>
                        <h2>Customer Service Platform</h2>
                       
                          
                    </div></div></div>
                

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Customer Information:<br>Destails</h2>
                    <p class="lead">Customer infomation needs to be tracked. Inclusding Customer Id, Name, billing address, shipping address, payment options, email address, security questions and security answers, and join date. </p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="{% static 'img/ipad.png' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Customer Information <br>CRUD</h2>
                    <p class="lead">Customer should be able to create an account. After loging in successfully, he or she should be able to view the detailed information, updata detailed information, and choose to delete this account.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="{% static 'img/dog.png' %}" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    

    </div>
    <!-- /.content-section-a -->

	
         
       
                       

 
        <!-- /.container --><!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                           <a href="{% url 'login:login' %}">login</a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
</footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js'%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.js'%}"></script>

</body>

</html>

Customer/templates/customer/nav.html
<h2>
<a href="{% url 'books_pc_multi_view:home' %}">Application Home</a>
{% if book %}
&gt; <a href="{% url 'books_pc_multi_view:book_view' book.id %}">{{ book.name }}</a>
{% endif %}
{% if title %}
&gt; {{ title }}
{% endif %}
</h2>

login/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Landing Page - Customer Service Platform</title>

    <!-- Bootstrap Core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" media="all" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css'%}" rel="stylesheet"/>

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css"/>
    <link href="//fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<style type="text/css">
body {
	background-color: #F0F0F0;
}
</style>
</head>

<body>
<div class="loginbk" text-center>
<div class="intro-header">
      <div class="container">


                <div class="col-lg-12">

                    <h1>Customer Service Platform</h1>
                    <h2>Login</h2>



                </div>
      </div>
</div>
<br>
<br>
<form method = 'post' enctype="multipart/form-data">
    {{uf.as_p}}
    <input type="submit" value = "submit" />
&nbsp;&nbsp;
    <a href="{% url 'Customer:customer_new' %}"> <input type="button" value="Register"></a>

</form>
    <br>
    <br>
</div>


</body>
</html>